services:
  mysql:
    image: mysql:8.0
    container_name: fgo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "fgo"
      TZ: "Asia/Shanghai"
    ports:
      - "8306:3306"
    volumes:
      - fgo-mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password

volumes:
  fgo-mysql-data:
